version: "3.9"

services:

  app:
    build: .
    container_name: ki_assistant_app
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - chroma_db:/app/chroma_db
      - uploads:/app/uploads
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama

volumes:
  chroma_db:
  uploads:
  ollama: